# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mythic/irs/l0/shape.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19mythic/irs/l0/shape.proto\x12\x13mythic.irs.l0.proto\"\x15\n\x05Shape\x12\x0c\n\x04\x64ims\x18\x01 \x03(\x05\"\xef\x05\n\rIterationSpec\x12*\n\x06\x64omain\x18\x01 \x01(\x0b\x32\x1a.mythic.irs.l0.proto.Shape\x12*\n\x06offset\x18\x02 \x01(\x0b\x32\x1a.mythic.irs.l0.proto.Shape\x12\x35\n\x11\x62uffer_shape_view\x18\x03 \x01(\x0b\x32\x1a.mythic.irs.l0.proto.Shape\x12*\n\x06\x66ilter\x18\x04 \x01(\x0b\x32\x1a.mythic.irs.l0.proto.Shape\x12*\n\x06stride\x18\x05 \x01(\x0b\x32\x1a.mythic.irs.l0.proto.Shape\x12\x32\n\x0e\x64omain_padding\x18\x06 \x01(\x0b\x32\x1a.mythic.irs.l0.proto.Shape\x12\x12\n\nstay_count\x18\x07 \x01(\x05\x12\x31\n\rwq_iterations\x18\x08 \x01(\x0b\x32\x1a.mythic.irs.l0.proto.Shape\x12\x31\n\rwq_sub_filter\x18\t \x01(\x0b\x32\x1a.mythic.irs.l0.proto.Shape\x12\x31\n\rwq_sub_stride\x18\n \x01(\x0b\x32\x1a.mythic.irs.l0.proto.Shape\x12-\n\tdim_order\x18\x0b \x01(\x0b\x32\x1a.mythic.irs.l0.proto.Shape\x12\x32\n\x0enum_iterations\x18\x0c \x01(\x0b\x32\x1a.mythic.irs.l0.proto.Shape\x12\x1b\n\x13windows_per_enqueue\x18\r \x01(\x05\x12\x1e\n\x16windows_per_tail_token\x18\x0e \x01(\x05\x12\x12\n\nreset_axis\x18\x0f \x01(\x05\x12\x32\n\x0esub_iterations\x18\x10 \x01(\x0b\x32\x1a.mythic.irs.l0.proto.Shape\x12.\n\nsub_stride\x18\x11 \x01(\x0b\x32\x1a.mythic.irs.l0.proto.Shapeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mythic.irs.l0.shape_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SHAPE._serialized_start=50
  _SHAPE._serialized_end=71
  _ITERATIONSPEC._serialized_start=74
  _ITERATIONSPEC._serialized_end=825
# @@protoc_insertion_point(module_scope)
