# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mythic/target_spec/resources.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mythic.target_spec import target_pb2 as mythic_dot_target__spec_dot_target__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"mythic/target_spec/resources.proto\x12\x12mythic.target_spec\x1a\x1fmythic/target_spec/target.proto\"\xcd\x02\n\x0eSaluParameters\x12\x32\n\x03ops\x18\x01 \x03(\x0b\x32%.mythic.target_spec.SaluParameters.Op\x12<\n\x0bvector_mode\x18\x02 \x01(\x0e\x32\'.mythic.target_spec.SaluSpec.VectorMode\x12<\n\x0bsigned_mode\x18\x03 \x01(\x0e\x32\'.mythic.target_spec.SaluSpec.SignedMode\x12\x11\n\tnum_beats\x18\x04 \x01(\x05\x12\x14\n\x0cshift_amount\x18\x05 \x01(\x05\x12\x19\n\x11multiply_constant\x18\x06 \x01(\x05\x1aG\n\x02Op\x12+\n\x02op\x18\x01 \x01(\x0e\x32\x1f.mythic.target_spec.SaluSpec.Op\x12\x14\n\x0cnum_operands\x18\x02 \x01(\x05\"[\n\x0bMmaBankRect\x12\x0e\n\x06inputs\x18\x02 \x01(\x05\x12\x0f\n\x07outputs\x18\x03 \x01(\x05\x12\x14\n\x0cinput_offset\x18\x04 \x01(\x05\x12\x15\n\routput_offset\x18\x05 \x01(\x05\"\xaf\x02\n\rMmaWeightArea\x12\x0f\n\x07\x62\x61nk_id\x18\x01 \x01(\x05\x12-\n\x04rect\x18\x02 \x01(\x0b\x32\x1f.mythic.target_spec.MmaBankRect\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x13\n\x0b\x62ias_inputs\x18\x04 \x01(\x05\x12\x18\n\x10\x61\x64\x63_offset_index\x18\x05 \x01(\x05\x12\x0e\n\x06\x62iases\x18\x06 \x01(\x0c\x12\x13\n\x0bright_shift\x18\x07 \x01(\x05\x12:\n\x0c\x62itspreading\x18\x08 \x01(\x0e\x32$.mythic.target_spec.BitSpreadingMode\x12\x16\n\x0escaling_factor\x18\t \x01(\x02\x12\x12\n\nfloat_data\x18\n \x03(\x02\x12\x14\n\x0c\x66loat_biases\x18\x0b \x03(\x02\"r\n\x11MmaWeightResource\x12+\n\x07tile_id\x18\x01 \x01(\x0b\x32\x1a.mythic.target_spec.TileId\x12\x30\n\x05\x61reas\x18\x02 \x03(\x0b\x32!.mythic.target_spec.MmaWeightArea*U\n\x10\x42itSpreadingMode\x12\n\n\x06Normal\x10\x00\x12\n\n\x06TwoWay\x10\x01\x12\x0b\n\x07\x46ourWay\x10\x02\x12\n\n\x06Nibble\x10\x03\x12\x10\n\x0cTwoWayNibble\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mythic.target_spec.resources_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BITSPREADINGMODE._serialized_start=942
  _BITSPREADINGMODE._serialized_end=1027
  _SALUPARAMETERS._serialized_start=92
  _SALUPARAMETERS._serialized_end=425
  _SALUPARAMETERS_OP._serialized_start=354
  _SALUPARAMETERS_OP._serialized_end=425
  _MMABANKRECT._serialized_start=427
  _MMABANKRECT._serialized_end=518
  _MMAWEIGHTAREA._serialized_start=521
  _MMAWEIGHTAREA._serialized_end=824
  _MMAWEIGHTRESOURCE._serialized_start=826
  _MMAWEIGHTRESOURCE._serialized_end=940
# @@protoc_insertion_point(module_scope)
