# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mythic/irs/l0/parameters.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emythic/irs/l0/parameters.proto\x12\rmythic.irs.l0*\x7f\n\x0cLauncherRole\x12\x17\n\x13LauncherRoleInvalid\x10\x00\x12\x18\n\x14LauncherRoleProducer\x10\x01\x12\x18\n\x14LauncherRoleConsumer\x10\x02\x12\"\n\x1eLauncherRoleProducerToProducer\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mythic.irs.l0.parameters_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LAUNCHERROLE._serialized_start=49
  _LAUNCHERROLE._serialized_end=176
# @@protoc_insertion_point(module_scope)
