# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mythic/irs/l0/vector_processing.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%mythic/irs/l0/vector_processing.proto\x12\x13mythic.irs.l0.proto\"\x92\x02\n\x0cInStreamSpec\"~\n\x02Op\x12\x0f\n\x0bNoOperation\x10\x00\x12\x16\n\x12MultiplyByConstant\x10\x01\x12.\n*MultiplyByConstantThenArithmeticShiftRight\x10\x02\x12\x07\n\x03\x41\x64\x64\x10\x03\x12\x07\n\x03Max\x10\x04\x12\r\n\tShiftLeft\x10\x05\"\x81\x01\n\nActivation\x12\x10\n\x0cNoActivation\x10\x00\x12\x08\n\x04Relu\x10\x01\x12\x0c\n\x08HardTanh\x10\x02\x12\x0f\n\x0bHardSigmoid\x10\x03\x12\r\n\tHardSwish\x10\x04\x12\r\n\tLeakyRelu\x10\x05\x12\t\n\x05\x43lear\x10\x06\x12\x0f\n\x0bLookUpTable\x10\x07\"\x9c\x02\n\x12InStreamParameters\x12\x30\n\x02op\x18\x01 \x01(\x0e\x32$.mythic.irs.l0.proto.InStreamSpec.Op\x12@\n\nactivation\x18\x02 \x01(\x0e\x32,.mythic.irs.l0.proto.InStreamSpec.Activation\x12\x10\n\x08\x63onstant\x18\x03 \x01(\x05\x12\r\n\x05shift\x18\x04 \x01(\x05\x12\x37\n\x0finput_precision\x18\x05 \x01(\x0e\x32\x1e.mythic.irs.l0.proto.Precision\x12\x38\n\x10output_precision\x18\x06 \x01(\x0e\x32\x1e.mythic.irs.l0.proto.Precision\"\xa2\x01\n\x0bInPlaceSpec\"\x92\x01\n\x02Op\x12\x0f\n\x0bNoOperation\x10\x00\x12\x07\n\x03\x41\x64\x64\x10\x01\x12\x0c\n\x08Subtract\x10\x02\x12\x0c\n\x08Multiply\x10\x03\x12\x07\n\x03Max\x10\x04\x12\r\n\tBitwiseOr\x10\x05\x12\x0e\n\nBitwiseAnd\x10\x06\x12\r\n\tLogicalOr\x10\x07\x12\x0e\n\nLogicalAnd\x10\x08\x12\x0f\n\x0b\x43learOnRead\x10\t\"\xb7\x01\n\x11InPlaceParameters\x12/\n\x02op\x18\x01 \x01(\x0e\x32#.mythic.irs.l0.proto.InPlaceSpec.Op\x12\x37\n\x0finput_precision\x18\x02 \x01(\x0e\x32\x1e.mythic.irs.l0.proto.Precision\x12\x38\n\x10\x62uffer_precision\x18\x03 \x01(\x0e\x32\x1e.mythic.irs.l0.proto.Precision*y\n\tPrecision\x12\x14\n\x10InvalidPrecision\x10\x00\x12\x12\n\x0e\x45ightBitSigned\x10\x01\x12\x14\n\x10\x45ightBitUnsigned\x10\x02\x12\x14\n\x10SixteenBitSigned\x10\x03\x12\x16\n\x12SixteenBitUnsigned\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mythic.irs.l0.vector_processing_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRECISION._serialized_start=977
  _PRECISION._serialized_end=1098
  _INSTREAMSPEC._serialized_start=63
  _INSTREAMSPEC._serialized_end=337
  _INSTREAMSPEC_OP._serialized_start=79
  _INSTREAMSPEC_OP._serialized_end=205
  _INSTREAMSPEC_ACTIVATION._serialized_start=208
  _INSTREAMSPEC_ACTIVATION._serialized_end=337
  _INSTREAMPARAMETERS._serialized_start=340
  _INSTREAMPARAMETERS._serialized_end=624
  _INPLACESPEC._serialized_start=627
  _INPLACESPEC._serialized_end=789
  _INPLACESPEC_OP._serialized_start=643
  _INPLACESPEC_OP._serialized_end=789
  _INPLACEPARAMETERS._serialized_start=792
  _INPLACEPARAMETERS._serialized_end=975
# @@protoc_insertion_point(module_scope)
