
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2026-05-27T13:44:34-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d7372689ac50f1ee34013a942b238f31becc9c47",
 "version": "0.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
