# Hey Emacs, this is a -*- makefile -*-
#++++++++++++++++++++++++++++ FileHeaderBegin +++++++++++++++++++++++++++++
# (c) videantis GmbH
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# FILENAME:             $RCSfile$
#
#--------------------------------------------------------------------------
#
# RESPONSIBLE:         Boris Boesler
#
# DESCRIPTION:         Makefile to "assemble" files generated by sp2 C compiler
#
# Id:                  $Id$
#
# LAST CHECKED IN BY:  $Author$
#
# NOTES:
#
# MODIFIED:
#
#+++++++++++++++++++++++++++++ FileHeaderEnd ++++++++++++++++++++++++++++++

# set tools used by this makefile

# precondition: compiler path is set up
# template includes generated header file compiler_main_asm.h
C_FILE_TEMPLATE = $(SP2CC_ROOT)/share/vspcc/c-templates/compiler_main.c
#ASSEMBLER_INCLUDE_DIR = $(SP2CC_ROOT)/share/vspgcc/assembler-includes
GENERATED_HEADER_FILE = compiler_main_asm.h

# max simulation time for one test 15 minutes = 15 * 60 seconds = 900 sec.
# update 19-05-2010: needs 1000 seconds
# update 20-05-2010: needs 100x seconds
ULIMIT_TIME_OPTION = -t 1200
ULIMIT = ulimit
LIMIT_SIM_TIME = $(ULIMIT) $(ULIMIT_TIME_OPTION)

# sp2 simulator and std. flags
ifeq ($(VIDSIM_VSP_CORE),)
VIDSIM_VSP_CORE=sp2.0
endif

# the result is written to address 0 in DMEM
SP2_SIMULATOR = vidsim
SP2_SIMULATOR_FLAGS = -cores $(VIDSIM_VSP_CORE) 1 -bd w 0 $(ADDITIONAL_SP2_SIMULATOR_FLAGS)
# dummy
SP2_SIMULATOR_DIR = .
# @@@ HACK
SP2_DIR = $(SP2_PROJ_DIR)/sp2

SP2_HOSTMEM_START = 0x0f000000
SP2_HOSTMEM_SIZE =  0x01000000
SP2_BOOT_ADDRESS = $(SP2_HOSTMEM_START)
SP2_HOST_LOAD_ADDRESS = $(SP2_HOSTMEM_START)


# sp2 assembler and std. options
SP2_ASSEMBLER = vspasm
SP2_ASSEMBLER_OLM_EXTERNAL_ADDRESS = 0x0f010000
#`expr $(SP2_HOSTMEM_START) + 2 * 32768`

SP2_ASSEMBLER_FLAGS = $(ADDITIONAL_SP2_ASSEMBLER_FLAGS)
# data-overlays
SP2_ASSEMBLER_FLAGS += --include-dir=$(SP2_ASM_DIR)/include


ifeq ($(CRT0_FILES), "COMPILER")
	SP2_ASSEMBLER_FLAGS += -I $(SP2_DIR)/include
endif
ifeq ($(CRT0_FILES), "VID_PLATFORM")
	SP2_ASSEMBLER_FLAGS += --olm-external-offset=$(SP2_ASSEMBLER_OLM_EXTERNAL_ADDRESS)
endif

SECTION_NAME = img_code

# extract time information
# old compiled simulation
#GREP_TIME_STR='cycle count is'
#SED_TIME_STR='s/cycle count is \([0-9]\{1,\}\)/\1/g'
# vid_sim
GREP_TIME_STR='cycles simulated'
SED_TIME_STR='s/\([0-9]\{1,\}\) cycles simulated.*/\1/g'


TIMINGS_FILE=$(shell date +%F)"-times.csv"

# assembler generates C code that must be compiled/linked as a shared object
# set up compiler and linker (system dependent)
THIS_OS = $(shell uname -s)
ifeq ($(THIS_OS),Linux)
ASLD_SO := $(CC) -std=c99 -O0 -g -Wall -fPIC -shared -lm
endif
ifeq ($(THIS_OS),Darwin)
ASLD_SO := $(CC) -std=c99 -m32 -O0 -ggdb -Wall -fPIC -lm -dynamic -bundle -flat_namespace -undefined suppress
endif

INCLUDE_DIRS = -I$(SP2_SIMULATOR_DIR) -I.

# create std IMEM file; avoid backslashes for easier cut&paste in terminal
%.imem:	%.s
	$(SP2_ASSEMBLER) $(SP2_ASSEMBLER_FLAGS) --out-asm=$*.out --out-nice-memory-imem=$*.nice.out --out-memory-map=$*.map --out-memory-dmem=$*.dmem --out-code=$*.imem --out-ext-code=$*.ovl.imem --out-asm-section=$*.section $<

#
#
#

#%.image:	%.imem %.dmem %.ovl.imem
#	cat $^ > $@
%.image:	%.imem
	cat $*.imem $*.dmem $*.ovl.imem > $@

#
# generate a trace file
#

ifeq ($(CRT0_FILES), "COMPILER")
%.trace:	%.imem
	$(SP2_SIMULATOR) $(SP2_SIMULATOR_FLAGS) -li $< -ld $*.dmem -map $*.map -tf $*.trace || true
endif
ifeq ($(CRT0_FILES), "VID_PLATFORM")
%.trace:	%.image
	$(SP2_SIMULATOR) $(SP2_SIMULATOR_FLAGS) \
	-hmem $(SP2_HOSTMEM_START) $(SP2_HOSTMEM_SIZE) \
	-lh $*.image $(SP2_HOST_LOAD_ADDRESS) \
	-boot $(SP2_BOOT_ADDRESS) \
	-map $*.map -tf $@ -trace_max_len 0
endif


#
# generate a stat file
#
ifeq ($(CRT0_FILES),"COMPILER")
%.stat:	%.imem
	$(LIMIT_SIM_TIME) && \
	$(SP2_SIMULATOR) $(SP2_SIMULATOR_FLAGS) -li $< -ld $*.dmem -map $*.map > $@ 2>&1 || true
else
ifeq ($(CRT0_FILES),"VID_PLATFORM")
%.stat:	%.image
	$(LIMIT_SIM_TIME) && \
	$(SP2_SIMULATOR) $(SP2_SIMULATOR_FLAGS) \
	-hmem $(SP2_HOSTMEM_START) $(SP2_HOSTMEM_SIZE) \
	-lh $*.image $(SP2_HOST_LOAD_ADDRESS) \
	-boot $(SP2_BOOT_ADDRESS) \
	-map $*.map > $@ 2>&1 || true
else
	echo "Unknown platform"
endif
endif


#
#
#
timings:	$(TIMINGS_FILE)

$(TIMINGS_FILE):	$(STAT_FILES)
	$(RM) $@
	for timefile in $^; do \
	    /bin/echo -n $$timefile: >> $@ ; \
	    grep $(GREP_TIME_STR) $$timefile | sed $(SED_TIME_STR) >> $@ ;\
	done
